version: '3.7'
services:
  sagu:
    build: .
    ports:
      - "81:80"
    volumes:
      - ./src:/var/www/sagu/
  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sagu
    volumes:
      - ./data:/var/lib/postgresql
